package com.market.astu.ui.theme

import androidx.compose.ui.graphics.Color

val PrimaryLight = Color(0xFF1D525B)
val OnPrimaryLight = Color(0xFFFFFFFF)
val PrimaryContainerLight = Color(0xFFDCEBE8)
val OnPrimaryContainerLight = Color(0xFF12363D)
val PrimaryDark = Color(0xFF8BC8C3)
val OnPrimaryDark = Color(0xFF08363D)
val PrimaryContainerDark = Color(0xFF173D45)
val OnPrimaryContainerDark = Color(0xFFDCEBE8)

val SecondaryLight = Color(0xFF5B6E73)
val OnSecondaryLight = Color(0xFFFFFFFF)
val SecondaryContainerLight = Color(0xFFDDE5E6)
val OnSecondaryContainerLight = Color(0xFF1D2D31)
val SecondaryDark = Color(0xFFB6C7CB)
val OnSecondaryDark = Color(0xFF223438)
val SecondaryContainerDark = Color(0xFF314347)
val OnSecondaryContainerDark = Color(0xFFDDE5E6)

val TertiaryLight = Color(0xFFC98335)
val OnTertiaryLight = Color(0xFF321B00)
val TertiaryContainerLight = Color(0xFFFFE1BE)
val OnTertiaryContainerLight = Color(0xFF4B2A00)
val TertiaryDark = Color(0xFFF0B56C)
val OnTertiaryDark = Color(0xFF4B2800)
val TertiaryContainerDark = Color(0xFF70440B)
val OnTertiaryContainerDark = Color(0xFFFFE1BE)

val ErrorLight = Color(0xFFBA1A1A)
val OnErrorLight = Color(0xFFFFFFFF)
val ErrorDark = Color(0xFFFFB4AB)
val OnErrorDark = Color(0xFF690005)

val BackgroundLight = Color(0xFFF6F1E8)
val OnBackgroundLight = Color(0xFF172126)
val SurfaceLight = Color(0xFFFFFBF6)
val OnSurfaceLight = Color(0xFF172126)
val SurfaceVariantLight = Color(0xFFEAE1D5)
val OnSurfaceVariantLight = Color(0xFF5F665F)
val OutlineLight = Color(0xFF8B857B)

val BackgroundDark = Color(0xFF091215)
val OnBackgroundDark = Color(0xFFEAF0ED)
val SurfaceDark = Color(0xFF10191D)
val OnSurfaceDark = Color(0xFFEAF0ED)
val SurfaceVariantDark = Color(0xFF1B272B)
val OnSurfaceVariantDark = Color(0xFFAFBBB8)
val OutlineDark = Color(0xFF7E8B88)
